import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../constants/theme";

const { width, height } = Dimensions.get("window");

export const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
    color: "black",
    justifyContent: "center",
    alignItems: "center",
  },

  GuyGuy: {
    width: 50,
    height: 50,
    marginLeft: 200,
    backgroundColor: "#006175",
    borderRadius: 100,
    resizeMode: "contain",
  },
  GuyStop: {
    width: 160,
    height: 160,
    marginRight: 0,
    backgroundColor: "#DBE9EC",
    borderRadius: 100,
    resizeMode: "cover",
  },
  GuyStopSm: {
    width: 30,
    height: 30,
    marginTop: -70,
    marginLeft: 280,
    backgroundColor: "#DBE9EC",
    borderRadius: 100,
    resizeMode: "cover",
  },
  NerdSm: {
    width: 70,
    height: 70,
    marginRight: 250,
    backgroundColor: "#006175",
    borderRadius: 100,
    resizeMode: "cover",
  },
  NerdSm2: {
    width: 50,
    height: 50,
    marginLeft: 250,
    backgroundColor: "hsl(195, 51.40%, 86.30%)",
    borderRadius: 100,
    resizeMode: "cover",
  },
  NerdSmm2: {
    width: 50,
    height: 50,
    marginTop: -50,
    marginLeft: 250,
    backgroundColor: "hsl(195, 51.40%, 86.30%)",
    borderRadius: 100,
    resizeMode: "cover",
    marginBottom: 40,
  },
  logo: {
    width: 200,
    height: 200,
    marginBottom: 20,
  },
  title: {
    fontSize: 20,
    color: "black",
    fontWeight: "bold",

    textAlign: "left",
    marginRight: 100,
    lineHeight: 24,
  },
  title2: {
    fontSize: 20,
    color: "black",
    fontWeight: "bold",
    textAlign: "left",
    marginRight: 130,
    lineHeight: 24,
  },
  description: {
    fontSize: 16,
    color: "gray",
    textAlign: "left",
    marginRight: 50,
    lineHeight: 24,
  },
  description2: {
    fontSize: 16,
    color: "gray",
    textAlign: "left",
    marginRight: 40,
    lineHeight: 24,
  },
  buttonContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    width: "100%",
  },
  nextButton: {
    backgroundColor: "#1C6758",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    width: "85%",
    alignItems: "center",
    marginBottom: 10,
  },
  skipButton: {
    backgroundColor: "#E5E7EB",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    width: "85%",
    alignItems: "center",
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
  skipText: {
    color: "#1F2937",
    fontWeight: "bold",
    fontSize: 16,
  },
  Disc: {
    flexDirection: "row",
    justifyContent: "center",
    gap: "between",
    alignItems: "center",
    marginTop: 20,
  },
  DiscText: {
    fontSize: 16,
    color: "gray",
    textAlign: "center",
  },
  DiscPrompt: {
    fontSize: 16,
    color: "#1C6758",
    textAlign: "center",
    fontWeight: "bold",
    marginLeft: 5,
  },
});
